services:
  - type: web
    name: video-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt && python app.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
