services:
  - type: web
    name: video-downloader
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget unzip curl gnupg && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
